version: "3.8"

services:
  web:
    build: ./server
    env_file:
      - ./server/.env
    restart: always
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - ./server/.env
    environment:
      #POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: